/* medicine cases, including anonymous cases */
set @first_suffix = 'Amar-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Bego-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Chry-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Dhal-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Edel-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Fuch-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Glad-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Gent-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Gera-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Hyac-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Hibi-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Inca-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Iris-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Jasm-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Kore-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Katt-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Leli-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Lave-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Made-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Marg-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Narc-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Orch-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Paar-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Papa-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Pioe-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Park-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Roos-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Teun-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Tulp-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Vioo-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Wate-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Zonn-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'Docent-'; source /tmp/buildCellulitis.sql;
set @first_suffix = 'DContr-'; source /tmp/buildCellulitis.sql;
/* TKD cases */set @W0_SUN = '2021-05-20';
set @W1_MON = '2021-05-21';
set @W1_TUE = '2021-05-22';
set @W1_WED = '2021-05-23';
set @W1_THR = '2021-05-24';
set @W1_FRI = '2021-05-25';
set @W1_SAT = '2021-05-26';
set @W1_SUN = '2021-05-27';
set @W2_MON = '2021-05-28';
set @W2_TUE = '2021-05-29';
set @W2_WED = '2021-05-30';
set @W2_THR = '2021-05-31';
set @W2_FRI = '2021-06-01';
set @first_suffix = 'Aapj-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Aren-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Beer-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Duif-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Fore-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Gira-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Gnoe-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Goud-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Haai-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Hams-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Hert-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Hond-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Kabe-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Kalf-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Kikk-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Koni-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Kraa-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Krab-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Leeu-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Muis-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Olif-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Poes-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Scha-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Tijg-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Toni-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Vark-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Vlie-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Vlin-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Wesp-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Zalm-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'Docent-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @first_suffix = 'DContr-'; source /tmp/buildDelierTKD.sql; source /tmp/buildCellulitisTKD.sql;
set @W0_SUN = '2021-06-20';
set @W1_MON = '2021-06-21';
set @W1_TUE = '2021-06-22';
set @W1_WED = '2021-06-23';
set @W1_THR = '2021-06-24';
set @W1_FRI = '2021-06-25';
set @W1_SAT = '2021-06-26';
set @W1_SUN = '2021-06-27';
set @W2_MON = '2021-06-28';
set @W2_TUE = '2021-06-29';
set @W2_WED = '2021-06-30';
set @W2_THR = '2021-07-01';
set @W2_FRI = '2021-07-02';
-- this should always be set this way anyway, but somehow we seem to be getting out of sync sometimes.
update orders set order_number = concat('ORD-',order_id);

-- even voor de zekerheid
SET @order_id = (select max(order_id) + 1 from orders);
update global_property set property_value = @order_id where property = 'order.nextOrderNumberSeed';

